### ISSUE TITLE
'volume' is not a docker command

### ISSUE THREAD

**Issue by dangmai** [clockworksoul/docker-gc-cron#1]
When I tried to use this image, it ran into the error:

```
docker: `volume` is not a docker command
```

I believe this is due to the fact that you use Docker 1.7 client, which does not have support that command yet.

**Comment by clockworksoul** [comment]
Sorry for the LOOONG delay in responding to this.

I updated the Docker client to `1.11.1`, which will do the trick.

**Comment by satyamuralidhar** [comment]
iam getting error like this while iam using for loop in python 
docker: 'i' is not a docker command.

**Comment by clockworksoul** [comment]
Hi Satya. Can you describe exactly what you're trying to do?

**Comment by satyamuralidhar** [comment]
iam trying to fetch which packages are running in multiple continaer using yaml file

this is my yaml file
---
docker:
  common: {
    registry: "{{ sds_registry_name }}",
  }
  dockbler: {
    name: "{{ namespace }}/fbb3c5191973",
    image_tag: "{{ image_tag }}",
  }
  repo_mirror: {
    name: "{{ namespace }}/mytask2",
    image_tag: "{{ image_tag }}",
  }
  repo_repofiles: {
    name: "{{ namespace }}/mytask3",
    image_tag: "{{ image_tag }}",
  }


this is my python file:

import yaml
import subprocess
stream = open("main.yaml",'r')
data = yaml.load(stream)
data = data["docker"].keys()
open("sample.txt","w+")
for i in data:
    print(i)
    cmd = 'docker i  | pip list --format columns  >> sample.txt'
    subprocess.call(cmd , shell = True)

data has been printed to sample.txt but getting error like this

repo_mirror
docker: 'i' is not a docker command.
See 'docker --help'
docker: 'i' is not a docker command.
See 'docker --help'
repo_repofiles
docker: 'i' is not a docker command.
See 'docker --help'
docker: 'i' is not a docker command.
See 'docker --help'
common
docker: 'i' is not a docker command.
See 'docker --help'
docker: 'i' is not a docker command.
See 'docker --help'
dockbler
docker: 'i' is not a docker command.

**Comment by clockworksoul** [comment]
Hi! I'm still not clear on what this has to do with docker-gc-cron, but I
do see one issue with your code:

cmd = 'docker i | pip list --format columns >> sample.txt'


You're trying to run `docker i` in a subprocess, but there really is no
such command.

Are you trying to run this inside a docker-gc-cron container?

**Comment by satyamuralidhar** [comment]
no iam running on my local mechine

while iam running that python code its calling yaml file . in that yaml I mentioned docker container
by using for loop its iterating all containers . for that iteration iam using i

**Comment by clockworksoul** [comment]
Ah, I see.

Your Docker command is a string literal. You'll need to concatenate your
value of i.

**Comment by satyamuralidhar** [comment]
k please know the script how to concat this
I have tried but not happend
