### ISSUE TITLE
Last docker-ce update says client is outdated

### ISSUE THREAD

**Issue by ilgigante77** [clockworksoul/docker-gc-cron#6]
Last docker-ce update says client is outdated:
**Message**:
```
b625bba4c0ca:/# docker-gc
Error response from daemon: {"message":"client version 1.23 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"}
```
**OS**:
```
elementary OS 7.1 Horus (GNU/Linux 6.5.0-26-generic x86_64)
Built on Ubuntu 22.04.3 LTS
```
**Docker**:
```
docker --version
Docker version 26.0.0, build 2ae903e
```

**Comment by ilgigante77** [comment]
Can you push a new image on Docker Hub?

**Comment by clockworksoul** [comment]
Yes absolutely! Done.

Matthew A. Titmus

About.me
<https://about.me/matthew.titmus?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>

***@***.***>

<https://www.linkedin.com/in/matthew-titmus/>

<https://github.com/clockworksoul>
